apiVersion: v1
kind: ReplicationController
metadata:
  labels:
    name: chhs
    tier: backend
  name: backend-controller
spec:
  replicas: 2
  template:
    metadata:
      labels:
        name: chhs
        tier: backend
    spec:
      containers:
      - image: portlandwebworks/chhs-backend:latest
        name: backend
        ports:
        - containerPort: 8080
        env:
          - name: SPRING_DATASOURCE_USERNAME
            valueFrom:
              secretKeyRef:
                name: chhs
                key: spring.datasource.username
          - name: SPRING_DATASOURCE_PASSWORD
            valueFrom:
              secretKeyRef:
                name: chhs
                key: spring.datasource.password
          - name: SPRING_DATASOURCE_URL
            valueFrom:
              secretKeyRef:
                name: chhs
                key: spring.datasource.url
