# frontend-service.yml
apiVersion: v1
kind: Service
metadata:
  name: frontend-service
  labels:
    name: chhs
    tier: frontend
spec:
  type: LoadBalancer
  ports:
    - port: 8080
      targetPort: 8080
  selector:
    name: chhs
    tier: frontend
